name: MTRaces
version: '1.0'
main: com.rune.mtraces.MTRaces
api-version: '1.19'
depend: [MTVehicles, WorldGuard]
commands:
  track:
    description: Track management commands
    usage: /<command> [args]
    permission: mtraces.command.track
  race:
    description: Race hosting commands
    usage: /<command> [args]
    permission: mtraces.command.race
